In [1]:
import tensorflow.compat.v1 as tf
tf.set_random_seed(777)
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
tf.compat.v1.disable_eager_execution()
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [19]:
#cost, optimizer 정의 - onehot encoding된 상태
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis)))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(200):
    sess.run(optimizer, feed_dict = {X: x_data, Y: y_data})
    if step % 20 == 0:
      print(step, sess.run(cost, feed_dict = {X: x_data, Y: y_data}))

  a = sess.run(hypothesis, feed_dict = {X: [[1,11,7,9]] })
  print(a, tf.arg_max(a, 1))

  



  b = sess.run(hypothesis, feed_dict = {X: [[1, 3,4,3]]})
  print(b, tf.arg_max(b,1))

0 127.36192
20 9.590678
40 68.002144
60 18.145985
80 20.16519
100 41.785023
120 14.476316
140 13.990038
160 20.824825
180 64.53967
[[2.7889946e-02 9.7211009e-01 2.8194275e-10]] Tensor("ArgMax_7:0", shape=(1,), dtype=int64)
[[0.2550659  0.743805   0.00112908]] Tensor("ArgMax_8:0", shape=(1,), dtype=int64)


In [24]:
#cross entropy 이용

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [25]:
cd '/content/gdrive/My Drive/AllDeepLearning/DeepLearningZeroToAll'

/content/gdrive/My Drive/AllDeepLearning/DeepLearningZeroToAll


In [60]:
#Classifier using softmax function
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('data-04-zoo.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape, y_data.shape)


(101, 16) (101, 1)


In [28]:
y_data

array([0., 0., 3., 0., 0., 0., 0., 3., 3., 0., 0., 1., 3., 6., 6., 6., 1.,
       0., 3., 0., 1., 1., 0., 1., 5., 4., 4., 0., 0., 0., 5., 0., 0., 1.,
       3., 0., 0., 1., 3., 5., 5., 1., 5., 1., 0., 0., 6., 0., 0., 0., 0.,
       5., 4., 6., 0., 0., 1., 1., 1., 1., 3., 3., 2., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 6., 3., 0., 0., 2., 6., 1., 1., 2., 6., 3., 1., 0.,
       6., 3., 1., 5., 4., 2., 2., 3., 0., 0., 1., 0., 5., 0., 6., 1.],
      dtype=float32)

In [31]:
import numpy as np
a = np.arange(12)
print(a)

a = a.reshape(3,4)

a

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [35]:
b = a.reshape(-1, 2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
c = a.reshape(2,-1)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
nb_classes = 7
X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

Y_one_hot = tf.one_hot(Y, nb_classes)

print("one-hot", Y_one_hot)

one-hot Tensor("one_hot_1:0", shape=(None, 1, 7), dtype=float32)


In [39]:
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape", Y_one_hot)

reshape Tensor("Reshape:0", shape=(None, 7), dtype=float32)


In [43]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name = 'weight') 
#input x 개수가 16개이므로 W.shape = [16,7]

b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

logits = tf.matmul(X,W) + b
hypothesis  = tf.nn.softmax(logits)



In [50]:
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels = Y_one_hot)
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis,1) #argmax, arg_max 둘다 똑같음 곧 사라질 예정이므로 argmax 사용 권장
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [70]:
result = []
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(2000):
    sess.run(optimizer, feed_dict = {X:x_data, Y:y_data})
    if step%100 == 0:
      loss, acc = sess.run([cost, accuracy], feed_dict = {X: x_data, Y: y_data})
      print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, loss, acc))  
      pred = sess.run(prediction, feed_dict = {X:x_data})


  for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))
    result.append((p,y))



Step:     0	Loss: 5.964	Acc: 28.71%
Step:   100	Loss: 0.810	Acc: 73.27%
Step:   200	Loss: 0.510	Acc: 86.14%
Step:   300	Loss: 0.372	Acc: 87.13%
Step:   400	Loss: 0.290	Acc: 91.09%
Step:   500	Loss: 0.235	Acc: 94.06%
Step:   600	Loss: 0.197	Acc: 94.06%
Step:   700	Loss: 0.168	Acc: 96.04%
Step:   800	Loss: 0.146	Acc: 97.03%
Step:   900	Loss: 0.129	Acc: 97.03%
Step:  1000	Loss: 0.115	Acc: 99.01%
Step:  1100	Loss: 0.104	Acc: 100.00%
Step:  1200	Loss: 0.094	Acc: 100.00%
Step:  1300	Loss: 0.086	Acc: 100.00%
Step:  1400	Loss: 0.080	Acc: 100.00%
Step:  1500	Loss: 0.074	Acc: 100.00%
Step:  1600	Loss: 0.069	Acc: 100.00%
Step:  1700	Loss: 0.065	Acc: 100.00%
Step:  1800	Loss: 0.061	Acc: 100.00%
Step:  1900	Loss: 0.058	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 Tr

In [72]:
acc = []
for r in result:
  pred, real = r
  if pred == real:
    acc.append(1)
  else: acc.append(0)
  

In [76]:
import statistics as s

s.mean(acc) #정확도 100%

1