In [ ]:
import tensorflow.compat.v1 as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


In [ ]:
tf.compat.v1.disable_eager_execution()
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)




## learning rate 0.1일 때

In [ ]:

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))


In [ ]:

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 3.40434 [[ 0.23075552 -0.2946202   1.6048746 ]
 [-0.41830462 -0.33050874 -2.0002625 ]
 [-1.4008963   0.05013004  0.21060304]]
1 1.8680595 [[ 0.25013426 -0.34668663  1.6375623 ]
 [-0.2685958  -0.56958383 -1.9108962 ]
 [-1.2458009  -0.17439778  0.28003547]]
2 1.4698318 [[ 0.25832424 -0.37578917  1.6584748 ]
 [-0.15832879 -0.7384352  -1.8523118 ]
 [-1.120835   -0.31697333  0.29764518]]
3 1.4341971 [[ 0.23628339 -0.36628598  1.6710125 ]
 [-0.21452732 -0.70818377 -1.8263648 ]
 [-1.142662   -0.27145237  0.27395126]]
4 1.4035456 [[ 0.22684103 -0.36954188  1.6837108 ]
 [-0.20060834 -0.7490669  -1.7994006 ]
 [-1.1005136  -0.29271144  0.25306183]]
5 1.3768449 [[ 0.20949508 -0.3636098   1.6951246 ]
 [-0.23232588 -0.7384057  -1.7783442 ]
 [-1.1000819  -0.26571888  0.22563766]]
6 1.3517613 [[ 0.19803593 -0.36402372  1.7069978 ]
 [-0.23147514 -0.7624987  -1.7551019 ]
 [-1.0702676  -0.27172282  0.20182721]]
7 1.3279265 [[ 0.1827492  -0.36006406  1.7183248 ]
 [-0.25305793 -0.7616436  -1.7343743 ]
 [

## learning rate = 10일 때


nan >> 발산함

In [ ]:

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=10).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))


In [ ]:

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 6.3102493 [[ 0.92305887  1.9815875  -1.7531285 ]
 [ 1.2732877   0.29393208 -0.8141473 ]
 [ 1.1361792   0.6705961   0.36766198]]
1 nan [[ -6.050599    5.205418    1.9966992]
 [-25.02237    16.589949    9.185494 ]
 [-25.346716   18.403717    9.117435 ]]
2 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
3 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
15 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
16 nan [[nan

# minmax 정규화 없이 regression 할 때

In [ ]:
import tensorflow.compat.v1 as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
print(xy.shape)

(8, 5)


In [ ]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]] #shape을 (~,1)로 해줄라고

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

print("x shape:", x_data.shape)
print("y_shape:", y_data.shape)

x shape: (8, 4)
y_shape: (8, 1)


y_data 만들 때 [-1]안하고 그냥 -1할 경우

In [ ]:
temp = xy[:, -1]
temp.shape

(8,)

In [ ]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10)
train = optimizer.minimize(cost)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer()) # 가중치 초기화해주기

  for step in range(101):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X : x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  468727860000.0 
Prediction:
 [[483421.66]
 [973444.06]
 [765719.4 ]
 [536688.44]
 [632562.25]
 [637885.1 ]
 [584626.25]
 [744408.44]]
1 Cost:  5.1187953e+16 
Prediction:
 [[-1.5959302e+08]
 [-3.2127683e+08]
 [-2.5273696e+08]
 [-1.7716734e+08]
 [-2.0880114e+08]
 [-2.1055856e+08]
 [-1.9298422e+08]
 [-2.4570722e+08]]
2 Cost:  5.5900396e+21 
Prediction:
 [[5.2739834e+10]
 [1.0617069e+11]
 [8.3520651e+10]
 [5.8547532e+10]
 [6.9001396e+10]
 [6.9582168e+10]
 [6.3774462e+10]
 [8.1197572e+10]]
3 Cost:  6.1046648e+26 
Prediction:
 [[-1.7428588e+13]
 [-3.5085535e+13]
 [-2.7600525e+13]
 [-1.9347821e+13]
 [-2.2802443e+13]
 [-2.2994366e+13]
 [-2.1075132e+13]
 [-2.6832831e+13]]
4 Cost:  6.66667e+31 
Prediction:
 [[5.7595130e+15]
 [1.1594491e+16]
 [9.1209676e+15]
 [6.3937498e+15]
 [7.5353757e+15]
 [7.5987995e+15]
 [6.9645627e+15]
 [8.8672724e+15]]
5 Cost:  7.280413e+36 
Prediction:
 [[-1.9033091e+18]
 [-3.8315561e+18]
 [-3.0141470e+18]
 [-2.1129010e+18]
 [-2.4901668e+18]
 [-2.5111260e+18]
 [-

### learning rate를 아무리 조정해줘도 cost 가 발산함 
-> 이거는 데이터 문제일 수 있음, 즉 회귀에서 정규화 과정 필요

# Regression with minmax normalization

In [ ]:
import tensorflow.compat.v1 as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)



In [ ]:

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)


[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [ ]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


# Launch the graph in a session.

with tf.Session() as sess:
  sess = tf.Session()
# Initializes global variables in the graph.
  sess.run(tf.global_variables_initializer())

  for step in range(101):
      cost_val, hy_val, _ = sess.run(
          [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
      print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
1 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
2 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
3 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
4 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
5 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
6 Cost:  3.6646028 
Prediction:
 [[1.8959911]
 [2.5416574]
 [2.4825053]
 [2.3672247]
 [2.4103918]
 [2.2758195]
 [2.5631897]
 [2.4086664]]
7 Cost:  3.6646028 
Prediction:
 [

#### 정규화하니까 잘 학습되는 것을 볼 수 있음